spring.application.name=notemap

spring.ai.openai.api-key = ${AI_API_KEY}

spring.ai.openai.base-url = ${OPENAI_BASE_URL}

spring.ai.openai.chat.options.model = ${CHAT_MODEL}

spring.ai.openai.embedding.enabled = true

spring.ai.openai.embedding.base-url=${EMBED_MODEL_API_URL}

spring.ai.openai.embedding.api-key=${EMBED_MODEL_API_KEY}

spring.ai.openai.embedding.model=${EMBED_MODEL_NAME}
#
#spring.ai.openai.chat.options.max-tokens = 2048


spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.ai.vectorstore.pgvector.index-type=HNSW
spring.ai.vectorstore.pgvector.distance-type= COSINE_DISTANCE
spring.ai.vectorstore.pgvector.dimensions=1024
spring.ai.vectorstore.pgvector.initialize-schema=true
#spring.ai.vectorstore.pgvector.max-document-batch-size=10000
