spring.application.name=notemap

spring.ai.openai.api-key = ${AI_API_KEY}

spring.ai.openai.base-url = ${OPENAI_BASE_URL}

spring.ai.openai.chat.options.model = ${CHAT_MODEL}
#
#spring.ai.openai.embedding.enabled = false
#
#spring.ai.openai.chat.options.max-tokens = 2048
